- play-ahc-ws-standalone/src/main/java/play/libs/oauth/OAuth.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/oauth/OAuth.scala
- project/Dependencies.scala
Signpost has a module that depends on commons-http4 for OAuth.  
This PR removes the dependency and uses the internal OAuthProvider that depends on HttpUrlConnection.
> Use Signpost's internal OAuthProvider and remove commons-http4

- README.md
- build.sbt
- project/CleanShadedPlugin.scala
- project/Dependencies.scala
- project/plugins.sbt
This PR is to resolve shading issues.  It makes sure the shaded-asynchttpclient and shaded-oauth libraries are all that are available to downstream users, and the input dependencies to the shaded libraries are not used.
This is trickier than it looks, because there are several things working against this.  
The "$HOME/.ivy2/cache" packages are sticky, and so doing an "sbt publishLocal" does not change downstream clients, because what's in cache will preceed what's in "$HOME/ivy2/local".  See https://github.com/sbt/sbt/issues/2687 for more details.
There is a note in SBT that says artifacts with SNAPSHOT in the name are not sticky, 
> The version number you select must end with SNAPSHOT, or you must change the version number each time you publish. Ivy maintains a cache, and it stores even …
> Manage shaded dependencies

- build.sbt
Filters out the dependencies so that shaded-oauth pulls nothing from maven.
> Filter out downstream dependencies from shaded-oauth

- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSClient.scala
The WS client will throw an exception when building a URL, when the 
underlying URL is invalid.  However, the exception throw is an NPE
which says things like "scheme is null" rather than saying that the
URL is invalid.
This fix looks for NPE coming from an asynchttpclient URI parsing and
then wraps it in an illegal argument exception, and details the API
as throwing IllegalArgumentException on invalid URL.
> Throw more explicit exception on invalid URL

- build.sbt
- project/Dependencies.scala
- project/build.properties
* Removes org.slf4j from the shaded-asynchttpclient library
* Removes gdata from shaded-oauth library
> Upgrade to Play 2.6.0-M4

- build.sbt
- integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcWSClientConfigFactory.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcUtilities.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Cache.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheAsyncConnection.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Debug.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/EffectiveURIKey.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/AhcWSCacheSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandlerSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheAsyncHandlerSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheAsyncHttpProviderSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheBuilderMethods.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
- project/CleanShadedPlugin.scala
- project/Dependencies.scala
- project/build.properties
Remove the dependency on `javax.cache.Cache`, and use a small trait.
This is because `javax.cache.Cache` API is disturbingly large and complex, meaning that other cache APis can't be adapted to it.  Given that the underlying functionality is so simple, it makes more sense to break it out completely, and rely on a very small Map based trait that can be easily adapted.
> Add a cache type and provide stub for it.

- integration-tests/src/test/java/play/libs/ws/ahc/HeaderAppendingFilter.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcWSCookie.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcWSCookie.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/java/play/libs/ws/WSCookie.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala
Fixes #83 and #97.
This adds the ability to manipulate cookies and other request attributes using a more uniform and consistent API.
1. `with*` methods were deprecated since they don't have a clear semantic when also compared with other Play APIs. The current behavior was kept.
2. `add*` methods were added and are supposed to append values to attributes, preserving existent values
3. `set*` methods were added and are supposed to completely replace the existent values, discarding them.
More tests were added (or just rearranged) to better ensure the behavior described above.
See discussion here: https://github.com/playframework/playframework/issues/7016
> More consistent with/add methods for both Scala and Java APIs

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
If we use a Source<ByteString> then we can get a conflict on Source<Multipart> in Play WS.
The correct thing to do is to make there be only one body that takes a type parameter, but this 
will work for now.
> Remove source methods as conflict with Multipart

- build.sbt
Fixed play-ws to find the sonatype staging repository (which is "com.typesafe", not "com.typesafe.play").  It is overridden with `sonatypeProfileName`.  
After merging this, we should be able to use "sbt release" by itself to do releases without having to go to oss.sonatype.org/#stagingRepositories and stage the repositories oureslves.
Also see https://github.com/xerial/sbt-sonatype/issues/35 and https://github.com/playframework/play-plugins/blob/master/redis/build.sbt#L41
> Fix sonatype release by adding sonatypeProfileName

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSResponse.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
Fixes #88 and #101.
Add methods to get header values, for both Scala and Java APIs.
> Add methods to get header values

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
Fixes #22.
Use `java.time.Duration` to set request timeout.
> Use a java.time.Duration to configure request timeout

- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
Remove deprecated methods -- we can add them in Play-WS as deprecated, but since this is a pre-1.0 standalone version, there's no reason it has to be deprecated in this project.
> Remove deprecated methods

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
Fixes https://github.com/playframework/playframework/issues/7444
Previously this was managed by setting the URL on the builder directly, but URI.create() makes assumptions about input which are not warrented, and the Javadoc says to use the constructor in the case of possibly invalid input.
See https://github.com/playframework/playframework/commit/50f391baf11aebe165c20ae7e9d8529fbfc7f21f#diff-5d483e96ccf6f80c115c5122cd8a8baaR50 for the attached blame.
> Use URL constructor instead of URI.create

- play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
- play-ws-standalone-json/src/test/scala/play/api/libs/ws/JsonBodyReadablesSpec.scala
Fixes https://github.com/playframework/play-ws/issues/150
> Add better JSON encoding support

- build.sbt
completely replacing the configuration properties resulted in errors when users
where using the unshaded AHC-Client in their applications together with play-ws.
As a workaround we take the original properties and _add_ our own properties to the
file. This way, the unshaded client still finds its properties while our own version can
be configured independently
> #87 add original + shaded configuration properties

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
Fixes possible NullPointerException when 'Content-Type' header is absent in HTTP response.
Fix the bug.
> fix possible NPE when 'Content-Type' header is absent in HTTP response

- project/plugins.sbt
Motivation is to get to the latest version of jarjar, to fix
a bug in shading of classes containing lambdas that is reported
under JDK 9.
Fixes #173
> Update sbt-assembly version

- build.sbt
- play-ahc-ws-standalone/src/test/scala/play/api/libs/oauth/OAuthSpec.scala
This should fix playframework/playframework#7629
/cc @wsargent
> Don't zap com.google.gdata

- build.sbt
- integration-tests/src/test/java/play/libs/ws/ahc/ByteStringRequestTest.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSResponse.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java
Fixes #175.
While this is supposed to be used with streamed responses we need to ensure the regular version also works. This changes the Java implementation to works as the Scala one.
> Fix problem with Java API getBodyAsSource

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheAsyncHandlerSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheableResponseSpec.scala
Fixes #182.
Avoid a `NullPointerException` when the `Content-Type` has no charset defined and response cache is enabled.
> Fix NPE in response.body when content type lacks charset

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
add case EmptyBody case.
Add EmptyBody case in CurlFormat trait.
An error occurs when using the following code.
```
ws.url(url).withRequestFilter(AhcCurlRequestLogger()).withQueryStringParameters("hey" -> "yo").get()
```
I can't found in Google search and Github issues.
> Add EmptyBody case

- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
Now AHC can return an `IllegalArgumentException` if a URI is invalid, so catch that and properly pass it on to the user.
Also `transform` expects a total function or else it will result in a `MatchError`.
> Catch IllegalArgumentException for invalid URI from AHC

- LICENSE
- NOTICE
Put the license in LICENSE and move the copyright notice to NOTICE.
The reasons for this change are:
1. It's how the Apache 2.0 license is applied: http://www.apache.org/dev/apply-license.html#new
2. It'll make GitHub recognise the project as Apache 2.0 licensed
> License and copyright notice shuffle

- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/Body.scala
This is a continuation of #188.
After trying to integrate with Play I realized that it's annoying to have these implicits in the companion object. That means to make it compatible with the non-standalone WS wrapper we have to do hacks to maintain backwards compatibility, in order to keep the methods on the `ws` package object (for source and binary compatibility) while also avoiding implicit resolution conflicts between the implicits on the companion and the implicits on the package object.
I also noticed that we actually tell people to import the readables and writables in the readme: https://github.com/playframework/play-ws#scala
Note that we have not yet done a release with the implicits in tho companion object yet so there are no compatibility issues with this PR specifically for …
> Remove implicits from BodyReadable and BodyWritable

- integration-tests/src/test/java/play/libs/ws/ahc/ByteStringRequestTest.java
- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSResponse.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcWSUtils.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StreamedResponse.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/DefaultBodyReadables.java
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyReadables.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
- Change the decoding of response body string back to the Play 2.5.x behavior: use the `charset` parameter if it exists, and fall back to `iso-8859-1` for `text/*` and `utf-8` otherwise. This is good enough most of the time for common charsets including `application/json`.
- Update the documentation for the `StandaloneWSResponse#body: String` and related methods to clarify that the decoding is only a best-guess effort and it should be used with caution.
- Make the decoding of the body use the same algorithm for `StreamedResponse` and `StandaloneAhcWSResponse`.
Fixes #187
> Add consistent String body handling and documentation

- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
Had to merge 2 commits according to [rules](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits).
The first commit's message is:
[Bug] Streamed WS requests do not apply filters at Scala API. Test that reproduces a bug.
This is the 2nd commit message:
[BugFix] Streamed WS requests also should be made with applied filters.
Same as at Java `play.libs.ws.ahc.StandaloneAhcWSRequest`.
_Fixes_ issue that I haven't create at bug tracker. Issue is: when streaming request/response with Scala API no filter applied.
_What does this PR do?_  - This PR brings Scala API to parity with Java API.
_Why did you take this approach?_  - Need some point where I can modify request and response in cohesion-ish way while streaming from remote WS. Had to use Scala because of my team …
> [BugFix] Streamed WS requests do not apply filters at Scala API.

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
Fixes #179 
Sets content type header if its presented when the body is set.
> Sets content type when the body is set if its presented.

- .travis.yml
- project/plugins.sbt
Add Java 9 to Travis build configuration.
This PR is a follow up to #210. Since we are now using sbt 1.0, we can also start to test against Java 9.
> Add Java 9 to travis configuration

- .travis.yml
- build.sbt
- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheAsyncConnection.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/Body.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/WSClientConfig.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
- project/build.properties
- project/plugins.sbt
Ref sbt/sbt-release#219
I don't think double publishing is the problem of sbt-release.
Part of the reason double publishing is happening is due to `crossScalaVersions := Seq(scala212, scala211)` set in artificial subprojects like `root` and `shaded`, and that these subprojects aggregate shaded Java subprojects. This means that when `+` traversal is on 2.11.x, it will propagate `publishSigned` to them, resulting in double publishing.
This adds `crossScalaVersions := Seq(scala212)` to `disablePublishing` so `root` and `shaded` do not cross build.
In addition, to avoid command propagation `aggregate(shaded)` was removed from `play-ahc-ws-standalone`.
See https://gist.github.com/eed3si9n/9a9e164072970a6daa4d318a28be7d73
> Fix double publishing

- build.sbt
It is also better to use `sonatypeRelease` because `sonatypeReleaseAll`
will promote all staged repositories for that organization profile. When
using `sonatypeRelease`, the release fails if there is more than one stage
repository. While this is annoying, it is better than have multiple releases
affecting each other.
https://github.com/xerial/sbt-sonatype
> No need to run cross run sonatypeRelease command

- build.sbt
`sonatypeProfileName` is configured at project level: 
https://github.com/xerial/sbt-sonatype/blob/2.3/src/main/scala/xerial/sbt/Sonatype.scala#L47
So setting it to root project instead of `ThisBuild`.
> Correct set sonatypeProfileName for root project

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
Fixes #48 
Ensure deterministic query param order when adding params through the WSRequest interface.
This does not address order when adding to a query param that already contains a value.
for example
```
req.addQueryParam("p1", "v1")
req.addQueryParam("p2", "v2")
req.addQueryParam("p1, "v3")
```
will yield `p1=v1&p1=v3&p2=v2` which is still not perfect but is at least deterministic
I wanted to make the minimal code change to achieve deterministic behaviour.
When generating digital signatures of urls (for example of an Authorization header) it's important to have a deterministic order to be able to correctly compute the digest.
https://github.com/playframework/playframework/pull/6884
https://github.com/playframework/play-ws/pull/102
> fix: make query param order deterministic when adding params

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
Fixes #231 and #232 
Adds new methods to the Java API for the StandaloneWSRequest to retrieve the request method and cookies
> Adding methods to retrieve current HTTP method+cookies in Java API

- play-ws-standalone-json/src/main/java/play/libs/ws/JsonBodyWritables.java
- play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyWritables.scala
Skip Json.stringify() calls in JsValue BodyWritable instances and go straight to byte arrays instead, then use that byte array directly instead of copying it into the ByteString instances. See https://github.com/playframework/playframework/pull/8375 for similar change in Play controllers rendering json results.
>  Skip JsValue Stringification in BodyWritables

- project/Dependencies.scala
This is a backported minor dependency update from `master`: 6120f7b60e3f461b0d15349a6337caea3e0b478d
Maybe we want some of those other patch updates on stable, but probably not the more significant updates... we can discuss here and I can update the pull request if needed.
> [1.1.x] Update cachecontrol to 1.1.3

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/FormUrlEncodedParser.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
Currently we will generate an AHC `Param` object with an empty key and value when there is an empty set of urlencoded form params. This is because we take the raw string and split it to parse it, and splitting an empty string results in a single empty key-value pair. To fix it we need to special case the empty string.
This should fix #257, since having the extra empty param makes the OAuth signature different.
> Don't generate an empty form param when given an empty params map

- build.sbt
- integration-tests/src/test/java/play/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- integration-tests/src/test/java/play/libs/ws/ahc/StandaloneWSClientSupport.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/StandaloneWSClientSupport.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSClientSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcCurlRequestLogger.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/BodyWritable.java
- play-ws-standalone/src/main/java/play/libs/ws/InMemoryBodyWritable.java
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/java/play/libs/ws/WSAuthInfo.java
This adds a Java version of curl-logger request filter that is present in the Scala APIs.
To do that, a number of changes we made in the Java version of `StandaloneWSRequest` so that we can access request information and create the `curl` command.
Also, tests were added to both Java and Scala version of the request filter.
> Java version of curl request filter

- project/Dependencies.scala
There is also an update available to Async HTTP Client, but it is being handled in #252.
> Minor dependencies updates

- build.sbt
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
Fixes #264
Adds support in the scala API for changing the `url` of the `WSRequest`.
Like @gmethvin, I've encountered a couple use cases where I'd like to modify the URL of an existing WSRequest.
1. Fixing URIs
In my `WSRequestFilter`s, I'd like to make use of `WSRequest.uri`, but it's unsafe (see #267). Today, I have a `WSRequestFilter` to sanitize the entire request prior to subsequent WSRequestFilters touching `WSRequest.uri`. In order to strip out query params and any other garbage from the URL, my `WSRequestFilter` has to rebuild the whole request from scratch. Additionally, it has to require a `WSClient` to do the job (`wsClient.url()`), which I hope is the same `WSClient` that originally used to build the request. Ugh!
2. Changing hostnames
We're cursed with …
> Add withUrl(String)

- build.sbt
- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/CookieBuilder.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSResponse.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ahc-ws-standalone/src/main/resources/reference.conf
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcWSUtils.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/CookieBuilder.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StreamedResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Debug.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigBuilderSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/AhcWSCacheSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheableResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- project/Dependencies.scala
Couldn't find a way to update branch name in the other PR, so had to create a new PR
* [Y] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [Y] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [Y] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [N/A] Have you added copyright headers to new files?
* [Y] Have you checked that both Scala and Java APIs are updated?
* [Y] Have you updated the documentation for both Scala and Java sections?
* [Y] Have you added tests for any changed functionality?
Upgrade Async-Http-Client to 2.4.4
Have access to connection stats through new class exposed from AsyncHttpClient
One major change around Cookie …
> Upgrade async-http-client to 2.4.4 to expose client connection stats

- build.sbt
- project/Dependencies.scala
Fixes https://github.com/playframework/playframework/issues/8566.
Update dependencies, mainly async-http-client, to have better support in Java 9+.
According to https://github.com/netty/netty/issues/7768 this was fixed in newer version of Netty and the (possible) fix is https://github.com/netty/netty/pull/7650. This is part of Netty 4.0.55.Final and [async-http-client is using 4.0.56](https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.39/pom.xml#L379). Since these dependencies are shaded, we need to update them here first, do a release and then update in Play.
> Update dependencies for stable version

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcLoggerFactory.scala
Fixes https://github.com/playframework/play-ws/issues/291
Makes loggerfactory use passed in name.
> Ensure logger factory uses name

- .travis.yml
- project/Dependencies.scala
Play-WS 2.0.0 should be using Play JSON 2.7.0, but I made the release in the inversed order.
This updates Play JSON here and also harmonizes some dependencies with what we have in Play itself.
> [2.7.x]: Update play json 2.7.0

- .travis.yml
- build.sbt
~~The supported flags are different for Scala 2.11 and Scala 2.12/2.13.~~
The scope here is now to fix the release process for Scala 2.13.0-M5. See the commits history.
> Fix release for Scala 2.13.0-M5

- bench/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequestBenchMapsBench.scala
- build.sbt
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- project/plugins.sbt
Optimizes `StandaloneAhcWSRequest.add*` methods from O(n) down to O(eC) by avoiding reconstructing maps from scratch.
I spotted this while benching https://github.com/playframework/play-ws/pull/288.
`StandaloneAhcWSRequest` uses immutable maps that support structural sharing, yet the implementations of `addQueryStringParameters((String, String)*)` and `addHttpHeaders(hdrs: (String, String)*)` rebuild the entire map on each call. For a request with *n* elements, appending a new one is an O(*n*) operation over an O(eC) data structure. Inserting *n* elements is O(*n²*).
Play 2.5 `WSRequest` has an O(eC) implementation, so this seems like new behavior in the pre-release of play-ahc-ws-standalone v2.
`AddQueryParamsBench` measures adding a single query param to a request that already has …
> Optimize StandaloneAhcWSRequest.add* methods.

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigBuilderSpec.scala
The WSRequest withCookies method suggests all cookies will be
discarded. This is not the case if the underlying http client has a
cookie store. Play ws also does not know about those cookies so for
example the AhcCurlRequestLogger does not log these cookies.
> [fix] don't use AHC cookie store

- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
- play-ahc-ws-standalone/src/main/resources/reference.conf
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
- project/Dependencies.scala
This pull request is a follow up of the discussion in https://github.com/playframework/play-ws/pull/307 where cookie store was completely disabled.
I also considered to turn-off follow redirects and cookie store and handle the state for each request without relying on the underlying library, but this would require a more extensive change. In the end, I've decided to add a more comprehensive test suite here so that we can better refactor the code in the future if we choose to follow this option.
Also updates Akka and Akka HTTP versions.
> Make it possible to enable/disable cookie store

- project/Dependencies.scala
- project/plugins.sbt
These are all safe to backport to 2.0.x. Grouping them to avoid adding more builds to Travis queue.
> [2.0.x]: Backport updates made by scala-steward

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
Fixes compile error
remove `Unit` 
```
Welcome to Scala 2.13.0-RC1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.
scala> Unit
^
error: `Unit` companion object is not allowed in source; instead, use `()` for the unit value
```
> fix compile error with Scala 2.13

- build.sbt
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
On streamed calls, once the connection is established if there's an error the error was not properly propagated.
This change introduces a mechanism so Stream Handlers use two promises: the first one is redeemed on stream starting and a second one that's redeemed when stream completes.
> Handle stream completion (propagate failures)

- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- play-ws-standalone-xml/src/main/java/play/libs/ws/XMLBodyReadables.java
- play-ws-standalone-xml/src/main/scala/play/api/libs/ws/XMLBodyReadables.scala
Fixes #328 
Supports any charset superior to utf-16 (if supported by java itself)
Look at Play.BodyParsers.tolerantXml
#328
> XML Readable : support any charset superior to utf-8

- .travis.yml
- build.sbt
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
- project/Dependencies.scala
Adds scala 2.13.0 support on the 2.0.x branch.
https://www.scala-lang.org/news/2.13.0
> Scala 2.13.0 support for 2.0.x

- build.sbt
This changes the scm.url to a browsable URL as recommended by the [POM Reference](https://maven.apache.org/pom.html#SCM). Scala Steward uses this URL to link to the updated dependency (as can be seen [here](https://github.com/mfirry/scala-http-clients/pull/76)) and a `git@` URL is not suitable for this purpose.
> Use a browsable URL for scm.url

- build.sbt
Aligns dynver settings with other projects. Namelly, we will stop using 'v' prefix for play-ws releases.
This should be merged in master. It can be added to #439, or we open a new PR for the merge.
> Adds dynver settings

- .travis.yml
Getting errors because the version Jabba asks for is too low:
```
Setting environment variables from .travis.yml
$ export JABBA_HOME=$HOME/.jabba
$ export TRAVIS_JDK=adopt@1.8.202-08
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
cache.1
Setting up build cache
$ java -Xmx32m -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
$ javac -J-Xmx32m -version
javac 11.0.2
Using Scala 2.12.8
before_install
1.86s$ curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
0.21s$ $JABBA_HOME/bin/jabba install $TRAVIS_JDK
No compatible version found for adopt@1.8.202-08
```
> Change travis to use latest JDK point version

- README.md
This is a workaround for https://github.com/playframework/play-ws/issues/418 although it does not fix the issue directly.
Add more documentation making it clear that the WSClient can take a live AsyncHttpClient directly.  
Companion piece to https://github.com/playframework/playframework/pull/10084
> [doc] Add note to show using AHC client directly

- build.sbt
- project/AutomaticModuleName.scala
Trying to introduce Automatic-Module-Name, as per https://github.com/playframework/playframework/pull/10087
Fixes nothing, added support for Java 9 Modules but adding Automatic-Module-Name to the MANIFEST.MF file
Add Automatic-Module-Name to the MANIFEST.MF so for anyone wanting to start moving to Java 9+ can start moving.
Same approach as https://github.com/playframework/playframework/pull/10087
> JPMS Automatic-Module-Name for all jars published

- .github/release-drafter.yml
- .scala-steward.conf
- .travis.yml
- README.md
- RELEASING.md
- build.sbt
- project/Dependencies.scala
- project/Publish.scala
- project/plugins.sbt
- release
Simplify the use of Mima, get the previous version from Dynver.
Make Travis release to Bintray on merge to master.
> Build: Mima, Dynver and publish settings; release to Bintray from Travis

- play-ws-standalone/src/main/scala/play/api/libs/ws/WSClientConfig.scala
N/A
Fixes the documentation links in scaladoc.
ssl-config repo moved to lightbend org from typesafehub.
https://github.com/lightbend/ssl-config/pull/65
> fix ssl-config url

- build.sbt
- integration-tests/src/test/java/play/libs/ws/ahc/JsonRequestTest.java
- integration-tests/src/test/java/play/libs/ws/ahc/XMLRequestTest.java
- integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
- play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
Fixes https://github.com/playframework/playframework/issues/10473
Replaces invalid #545
Backport: #553
(To make review easy I recommend you to review commit after commit)
Right now the config `play.ws.ahc.disableUrlEncoding` **does nothing**.
https://github.com/playframework/play-ws/blob/2e42acc58ef276c0587eb44c1925755ee816ed8f/play-ahc-ws-standalone/src/main/resources/reference.conf#L29-L30
Technically, the config does get [parsed and read](https://github.com/playframework/play-ws/blob/v2.1.2/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala#L100) and it will also be set onto the _client_:
https://github.com/playframework/play-ws/blob/735b38213011d4905426709205335a515a0333d7/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala#L202
But now …
> Make play.ws.ahc.disableUrlEncoding actually do something useful

- .travis.yml
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSClientSpec.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- project/Dependencies.scala
prepare Scala 3
```
scala> Option(1).map{ a => a }
val res0: Option[Int] = Some(1)
scala> Option(1).map{ a: Int => a }
1 |Option(1).map{ a: Int => a }
|                      ^
|parentheses are required around the parameter of a lambda
|This construct can be rewritten automatically under -rewrite -source 3.0-migration.
```
> add parentheses for lambda param

- integration-tests/src/test/scala/play/AkkaServerProvider.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
add explicit types
prepare Scala 3
```
$ scala -version
Scala compiler version 3.0.1 -- Copyright 2002-2021, LAMP/EPFL
$ scala 
scala> implicit val a = 2
1 |implicit val a = 2
|             ^
|             type of implicit definition needs to be given explicitly
```
> add explicit type annotations for implicit val

- build.sbt
Fixes warnings 
```
/home/travis/build/playframework/play-ws/build.sbt:122: warning: method copy in class AssemblyOption is deprecated (since 1.0.0): copy method is deprecated; use withIncludeBin(...) etc
assembly / assemblyOption ~= (_.copy(includeScala = false)),
^
/home/travis/build/playframework/play-ws/build.sbt:125: warning: method copy in class AssemblyOption is deprecated (since 1.0.0): copy method is deprecated; use withIncludeBin(...) etc
_.copy(includeScala = false)
^
/home/travis/build/playframework/play-ws/build.sbt:223: warning: method copy in class AssemblyOption is deprecated (since 1.0.0): copy method is deprecated; use withIncludeBin(...) etc
assembly / assemblyOption := (assembly / assemblyOption).value.copy(includeBin = false, includeScala = false),
^ …
```
> fix warnings in build.sbt

- .github/workflows/release-drafter.yml
- .travis.yml
- README.md
- RELEASING.md
- build.sbt
references #596
I've already done the renaming, so this just changes the repo contents to reflect the new reality
> rename `master` branch to `main`

- .travis.yml
- README.md
- build.sbt
- project/Dependencies.scala
> Upgrade to latest akka 2.6.16

- .travis.yml
- RELEASING.md
- build.sbt
- project/plugins.sbt
This is a manual backport of #599
> Remove old bintray publishing for 2.1.x

- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/AhcWSCacheSpec.scala
- prepare Scala 3. separate #604
```
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/AhcWSCacheSpec.scala:25:27 
[error] 25 |      implicit val cache = new AhcHttpCache(new StubHttpCache(), true)
[error]    |                           ^
[error]    |value cache needs result type because its right-hand side attempts implicit search
```
> add explicit type annotations for implicits

- .scalafmt.conf
prepare scalafmt 3.x
https://app.travis-ci.com/github/playframework/play-ws/jobs/553942436#L456
https://scalameta.org/scalafmt/docs/configuration.html#docstringsstyle--asterisk
```
[error] Invalid config: 3 errors
[error] [E0] <input>:9:0 error: Type mismatch;
[error]   found    : String (value: "JavaDoc")
[error]   expected : Object
[error]     "docstrings" : "JavaDoc",
[error] ^
```
> Update scalafmt `docstrings` setting

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigBuilderSpec.scala
- project/Dependencies.scala
We need to upgrade ssl-config in play-ws 2.1.x to 0.6.0, because akka [did the same a couple of days ago](https://github.com/akka/akka/commit/4fb7bd9bfad32c7a7ddf3b3de430e66ffccd51a9), and because Play's cron build for the 2.8.x branch uses the latest akka snapshot, the build is now broken: https://app.travis-ci.com/github/playframework/playframework/jobs/554697000#L1703
```
Exception in thread "specs2-2" java.lang.NoSuchMethodError: com.typesafe.sslconfig.ssl.SSLLooseConfig.allowWeakProtocols()Z
```
We need to wait for akka 2.6.19 however.
> [2.1.x] ssl-config 0.6.0 (like akka 2.6.19)

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .mergify.yml
> Migrate check RRs for `2.1.x` to GitHub Actions

- project/Dependencies.scala
Getting rid of the akka SNAPSHOT version.
akka did _not_ upgrade to ssl-config 0.6.x because it has binary compatibility issues with 0.4.x. Actually it got upgraded first, see https://github.com/akka/akka/pull/31046, then it got partially reverted, see https://github.com/akka/akka/pull/31252.
Partially reverted means that only the dependency was downgraded again, however akka itself removed methods and classes not available anymore in ssl-config 0.6.x, so akka 2.6.19 itself works nicely with ssl-config 0.6.x. However they didn't want to upgrade to latest ssl-config to not break libraries depending on akka and which also use removed methods and/or classes from ssl-config 0.4.3.
For play-ws stable branch 2.1.x I play the same game now, keeping the dependency versions like they were in the …
> [2.1.x] Keep dependencies like in v2.1.7

- project/Dependencies.scala
cachecontrol 2.2.0 pulls in the correct `scala-parser-combinators` version for Scala 2 or 3 already: https://github.com/playframework/cachecontrol/blob/2.2.0/project/Dependencies.scala#L15-L21
I think the excludes you added here are not necessary anymore. I think you added them because you started your pull request #604 long time before cachencontrol 2.2.0 was released, because before that it was just using `1.1.2`, which had no support for Scala 3.
> No need to exclude scala-parser-combinators anymore

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .mergify.yml
- build.sbt
Almost the same like https://github.com/playframework/play-json/pull/705
> Switch to reusable workflows

- integration-tests/src/test/java/play/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcUtilities.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/FormUrlEncodedParser.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheAsyncConnection.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Debug.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
fix warnings.
- https://github.com/playframework/play-ws/pull/603 play-ws drop Scala 2.12 support.
- JavaConverters deprecated since Scala 2.13 https://github.com/scala/scala/blob/v2.13.8/src/library/scala/collection/JavaConverters.scala#L78
> use jdk.CollectionConverters instead of deprecated JavaConverters

- integration-tests/src/test/java/play/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSClientSpec.scala
- integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
- project/Dependencies.scala
- play-ws dropped Scala 2.12 support https://github.com/playframework/play-ws/pull/603
- https://github.com/scala/scala/blob/2.13.x/src/library/scala/jdk/ scala std lib has some converters since Scala 2.13
> remove scala-java8-compat dependency

- .github/PULL_REQUEST_TEMPLATE.md
This removes the Lightbend CLA from the checklist, to avoid confusion.
> Removed Lightbend CLA from PR template

- integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
avoid specs2-mock `returns` DSL. use mockito-core `when` and `thenReturn` directory.
https://github.com/etorreborre/specs2/blob/SPECS2-4.19.2/mock/shared/src/main/scala/org/specs2/mock/mockito/MockitoStubs.scala#L41-L43
play-ws using `specs2-mock` version 4.x with `CrossVersion.for3Use2_13`.
but specs2-mock does not available in latest specs2 5.x version.
This changes prepare for migrate to latest specs2 or another testing library(scalatest?)
> avoid specs2-mock `returns` DSL

- integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
- integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigBuilderSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSClientConfigParserSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
- project/Dependencies.scala
remove specs2-mock and specs2-junit dependency
- same motivation as https://github.com/playframework/play-ws/pull/748 This changes prepare for migrate to latest specs2 or another testing library(scalatest?)
> remove specs2-mock and specs2-junit dependency

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
fix warning
https://github.com/AsyncHttpClient/async-http-client/blob/7a370af58dc8895a27a14d0a81af2a3b91930651/client/src/main/java/org/asynchttpclient/RequestBuilder.java#L43-L46
```
[warn] /home/runner/work/play-ws/play-ws/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala:223:19: constructor RequestBuilder in class RequestBuilder is deprecated
[warn]     val rb      = new RequestBuilder(request)
[warn]                   ^
```
> fix warning in CachingAsyncHttpClient

- project/Dependencies.scala
https://github.com/scala/scala-xml/releases/tag/v1.3.1
Avoids `StackOverflowError`.
> [2.1.x] scala-xml 1.3.1

- play-ws-standalone-xml/src/main/scala/play/api/libs/ws/XMLBodyReadables.scala
Fixes #488
WS API `response.xml` is vulnerable to XXE injection attacks. Tracing the issue it seems to have been introduced a few years ago when the custom XML parser was replaced by a default one without the `xercesSaxParserFactory`.
I have reverted the code to using the custom factory parser.
> Prevent XXE injection when parsing XML

- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
Fixes #802. Please also port this fix to 2.2.x branch.
Also this fix removed usage of `scala.concurrent.ExecutionContext.Implicits.global`.
> restore streaming in StandaloneWSRequest.stream()

- build.sbt
- project/Dependencies.scala
Just cherry-picking a commit from #829
> Small workaround that allows us to upgrade akka independent of Play

- build.sbt
Fixes
- #862
The problem was introduced in 0efba3c556f65e3ba54c9b0ea9319aa58d86f3aa were the assumption was made that the latest netty-reactive-streams version 3 needs to be shaded, however turns out that latest asynchttpclient 2.x [still depends on netty-reactive-streams 2.x](https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.12.3/pom.xml#L339-L340), so the changing the shading rename rule `com.typesafe.netty.**` to `org.playframework.netty.**` does not make sense and ruines the original shading...
With this fix the shading works again (tested locally).
Side note:
Upcoming async-http-client v3 does not depend on `netty-reactive-streams` anymore, so as soon as we upgrade, we can remove the corresponding shading settings:
- …
> Correctly shade netty-reactive-streams

- project/Dependencies.scala
Latest AsyncHttpClient v2 (currently 2.12.3) comes with an outdated netty-reactive-streams dependency: [2.0.4](https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.12.3/pom.xml#L473).
Meanwhile we are on 2.0.12, which besides upgrading netty to a very recent version, also brings some fixes:
https://github.com/playframework/netty-reactive-streams/compare/netty-reactive-streams-parent-2.0.4...netty-reactive-streams-parent-2.0.12
However, I will not include this PR right now in the next play-ws patch release, because I am not sure if such an upgrade would cause problems (specially because netty will be bumped from 4.1.43 to 4.1.104 which is, for netty, quite a big jump.
I keep this as a draft for later, as a reminder...
> Use latest netty-reactive-streams version, ahc comes with outdated one

- play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
- play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StreamedResponse.scala
- play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
- play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala
> [3.0.x] StreamedResponse `headers` map is now case insensitively

- project/Dependencies.scala
Need to upgrade Pekko in https://github.com/playframework/playframework/ hand in hand later.
Will bump later again for another milestone release.
> Downgrade pekko (only temporarily in the main branch)
