build.sbt
project/plugins.sbt

Uses the play-iteratees 2.6.1-SNAPSHOT which has 2.12 version

Add in 2.12 support

---

build.sbt
project/Dependencies.scala

Remove play-iteratees and limit libraries to where they are used.

Remove unneeded libraries and project dependencies

---

build.sbt
play-ahc-ws-standalone/src/main/scala/play/api/libs/oauth/OAuth.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcWSCookie.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/OrderPreserving.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/XML.scala
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/Config.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSClient.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StreamedResponse.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala
project/plugins.sbt

Add scalariform formatting to project.

Add scalariform

---

build.sbt
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSConfigBuilderSpec.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSResponseSpec.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WithBody.scala

Add more `withBody` methods to StandaloneWSRequest.

Add richer body to WSRequest

---

play-ahc-ws-standalone/src/it/java/playwsclient/JavaIntegrationTest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcLoggerFactory.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigSpec.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/BodyWritable.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala

Adds a type class implementation for posting different kinds of bodies.

Add BodyWritable

---

README.md
build.sbt
play-ahc-ws-standalone/src/it/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java

Add variance and add deprecation annotation and stricter compile time warnings.
Also adds defaults to read from ConfigFactory.load by default.

Add variance hack for java

---

play-ahc-ws-standalone/src/it/java/play/libs/ws/ahc/HeaderAppendingFilter.java
play-ahc-ws-standalone/src/it/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/it/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcWSClientConfigFactory.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
play-ws-standalone/src/main/java/play/libs/ws/WSRequestExecutor.java
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSClientConfig.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSRequestFilter.scala
version.sbt

Fixes the type variance in WSRequestFilter.
Adds getContentType to WSRequest in Scala and Java APIs.

Fix the type variance

---

play-ahc-ws-standalone/src/it/java/play/libs/ws/ahc/HeaderAppendingFilter.java
play-ahc-ws-standalone/src/it/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/it/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ws-standalone/src/main/java/play/libs/ws/WSRequestExecutor.java
play-ws-standalone/src/main/java/play/libs/ws/WSRequestFilter.java
play-ws-standalone/src/main/scala/play/api/libs/ws/WSRequestFilter.scala

Implement filters using java.util.Function and scala.Function.  Fixes https://github.com/playframework/play-ws/issues/55

Better filters

---

play-ahc-ws-standalone/src/it/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSRequestFilter.scala

Add a function to type apply method for `WSRequestFilter` for adhoc filters.

Add singleton apply for filter

---

integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala

Add extra test for AhcWSClient with a cache

Add integration caching test

---

integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/EffectiveURIKey.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/CacheBuilderMethods.scala

Isolate the cache logic and centralize things to the client

Isolate cache

---

README.md

Documentation - README file
see above

update version to 1.0.0-M6 in sbt instructions

---

play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala

Preserve existing headers when setting request body

---

project/Dependencies.scala

Upgrade to asynchttpclient 2.0.32

---

README.md
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ws-standalone/src/main/java/play/libs/ws/WSResponseHeaders.java
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala

This does some small API changes and updates the README Java example to compile and use the updated APIs.

Small api chances

---

integration-tests/src/test/scala/play/AkkaServerProvider.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala

Tests will run with a random port instead of 9000 and also don't need to run sequentially anymore.

Tests running with a random port and non-sequentially

---

integration-tests/src/test/java/play/libs/ws/ahc/ByteStringRequestTest.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
play-ws-standalone/src/main/java/play/libs/ws/DefaultBodyWritables.java

Adds in the form data mapping for the Java API.

Add form data

---

integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Cache.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/cache/StubHttpCache.scala

Add Future to Cache interface, fixes https://github.com/playframework/play-ws/issues/133

Add Future to Cache interface

---

project/Dependencies.scala

Upgrade dependencies

---

play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
play-ws-standalone-json/src/test/scala/play/api/libs/ws/JsonBodyReadablesSpec.scala

Cherry pick from https://github.com/playframework/play-ws/pull/151

Add better JSON encoding support

---

play-ws-standalone-json/src/main/java/play/libs/ws/JsonBodyReadables.java
play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
play-ws-standalone-json/src/test/scala/play/api/libs/ws/JsonBodyReadablesSpec.scala

Move from the Jackson to Json.parse():
https://github.com/playframework/play-ws/pull/151#issuecomment-311054502 and https://github.com/playframework/play-ws/pull/151#discussion_r123924518

Use Json.parse for bodyreadables

---

build.sbt
project/plugins.sbt

Fixes https://github.com/playframework/play-ws/issues/125 but needs to be integrated after 1.0.0 release.

Add note for mima integration

---

build.sbt
project/plugins.sbt

Backport https://github.com/playframework/play-ws/pull/130

Backport #130

---

build.sbt

Backport of https://github.com/playframework/play-ws/pull/149 to 1.x.x

Backport #149

---

play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala

Backport https://github.com/playframework/play-ws/pull/161

fix possible NPE when 'Content-Type' header is absent in HTTP response

---

project/plugins.sbt

[1.x.x]: Update sbt-assembly version (#174)

---

.travis.yml
build.sbt

In my non-scientific benchmark (time reported by sbt), compile times comes down from ~30s to ~20.
Amazing work from Scala team.

Update to Scala 2.12.3

---

project/Dependencies.scala

So we can get this fix: https://github.com/AsyncHttpClient/async-http-client/pull/1459

Update AHC to 2.0.36

---

play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala

Just some small clarifications in docs/tests

Update descriptions in tests

---

.travis.yml
build.sbt
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheAsyncConnection.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/Body.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSClientConfig.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
project/build.properties
project/plugins.sbt

This change upgrades all SBT plugins -- including [sbt-scalariform]
[sbt-scalariform] configuration has changed.

SBT version 0.13.15 --> 1.0.4

---

project/Dependencies.scala

* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ x] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [ x] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
Those who depend on akka streams and akka-http has to fight with eviction warning if they are using play-ws. This upgrades akka streams and akka-http to the latest version.

Upgrade akka libraries to current release

---

play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala

fix unclosed quote on Authorization: Basic header

---

build.sbt

The release process is not working. First not publishing to Sonatype and later not having a `publishTo` value. This PR hopefully fix both problems.

Fix release process

---

build.sbt

Avoid cross build for shaded projects

---

.travis.yml
build.sbt
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AsyncCachingHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/BackgroundAsyncHandler.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheAsyncConnection.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CachingAsyncHttpClient.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/Body.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WS.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSClientConfig.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
project/build.properties
project/plugins.sbt

Reverts sbt 1 changes since we are having problems releasing play-ws (see #240). This has also reverted some formatting changes made at #210.

Revert sbt 1 chances

---

build.sbt
project/build.properties

Fixes #240.
This pull request forward ports pull request #243.
/cc @eed3si9n.

[master]: forward port 243 - fix double publishing.

---

build.sbt

1. Support build on Windows.
2. Merge or remove some redundant `settings` blocks.

Minor build fixes

---

.travis.yml
build.sbt
integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
project/Dependencies.scala

Add support to Scala 2.13.0-M3

---

.github/ISSUE_TEMPLATE.md

Set up issue template to point to https://discuss.lightbend.com/c/play/

Update with discuss site

---

build.sbt
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcCurlRequestLogger.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala

Updates #129 against the current master.

Clean up API to return Optional and use duration

---

play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala

fix procedure syntax
add explicit `: Unit = `
procedure syntax is deprecated 
https://github.com/scala/scala/commit/1d4d901fcea0a162cd139836b246e85cc0130a6b

fix procedure syntax

---

play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala

Fix getBody -> body scaladoc in StandaloneWSResponse

---

.travis.yml
build.sbt

Scala 2.12.4 --> 2.12.6
latest version of Scala 2.12.x
n/a
n/a

Scala 2.12.4 --> 2.12.6

---

play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/AhcCurlRequestLogger.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/CacheableResponse.scala
play-ws-standalone/src/main/java/play/libs/ws/DefaultBodyWritables.java

This is a small PR I did in my spare time. I had Intellij's code analysis look at the code, then went over the results.
The biggest change is the use of a static inner class for AsyncCompletionHandler. As Intellij's description states:
>A static inner class does not keep an implicit reference to its enclosing instance. This prevents a common cause of memory leaks and uses less memory per instance of the class. 
Other than that, some small changes of which Intellij states they're more performant.

Suggestions based on Intellij's code analysis.

---

project/Dependencies.scala

latest play-json version
latest play-json version

play-json 2.6.10

---

.travis.yml
build.sbt

Scala 2.12.6 -> 2.12.7
Scala 2.12.6 -> 2.12.7
Scala 2.12.6 -> 2.12.7
n/a

Scala 2.12.7

---

project/plugins.sbt

latest [sbt-assembly] -- improved compatibility with JDK 11
latest [sbt-assembly] -- improved compatibility with JDK 11
latest [sbt-assembly] -- improved compatibility with JDK 11
https://github.com/sbt/sbt-assembly/releases

sbt-assembly 0.14.8

---

project/Dependencies.scala

Update ssl-config to version 0.3.2.
https://github.com/lightbend/ssl-config/releases/tag/v0.3.2

Update ssl-config to version 0.3.3

---

project/Dependencies.scala

Update ssl-config to 0.3.4

---

project/Dependencies.scala

Fixes https://github.com/playframework/play-ws/issues/265
Upgrading the cachecontrol dependency, pulling in https://github.com/playframework/cachecontrol/pull/30 to not cache POST responses by default

Upgrade cachecontrol to 1.1.4

---

.travis.yml
build.sbt
project/build.properties

[1.1.x]: Build using AdoptOpenJDK 8 & 11 (#296)

---

build.sbt

Configure binary compatibility check against version 2.0.0.

[2.0.x]: Configure binary compatibility check

---

project/Dependencies.scala

play-json 2.7.1

---

project/Dependencies.scala

scala-java8-compat 0.9.0 (latest version)
scala-java8-compat 0.9.0 (latest version)
n/a
n/a

scala-java8-compat 0.9.0

---

.travis.yml
build.sbt
play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala

Follow up of #313. Fix MiMa configuration and other changes suggested by @ignasi35.

Fix MiMa configuration

---

build.sbt

`sbt release` is failing since it is trying to cross-publish the shaded libraries.

Do not cross publish shaded libraries

---

version.sbt

Fix snapshot version

---

build.sbt
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/Streamed.scala

Forward port of https://github.com/playframework/play-ws/pull/340

Handle stream completion (propagate failures)

---

build.sbt
project/plugins.sbt
version.sbt

This project uses tags prefixed with a 'v'. No extra configuration needed therefore.

Start to use dynver

---

project/Dependencies.scala

Update to Akka 2.6.0-M8

---

.travis.yml
build.sbt
project/Dependencies.scala

- https://github.com/AsyncHttpClient/async-http-client/pull/1667

[1.1.x]: Update Async-Http-Client to version 2.0.40

---

build.sbt
project/Dependencies.scala

This is using a snapshot just to test if there are some corner cases we should pay attention to.
Draft since 2.6.0-RC1 does not exist yet. :-)

Akka 2.6.0 RC1

---

project/plugins.sbt

I am also harmonizing the version of other plugins with Play and Lagom.

Update sbt-pgp to version 2.0.0

---

integration-tests/src/test/java/play/libs/ws/ahc/JsonRequestTest.java
integration-tests/src/test/resources/test.json
integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
play-ws-standalone-json/src/main/java/play/libs/ws/JsonBodyReadables.java
play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
play-ws-standalone-json/src/test/scala/play/api/libs/ws/JsonBodyReadablesSpec.scala

fixes https://github.com/playframework/playframework/issues/9602

Fixes inconsistent json parsing

---

build.sbt

Configure mima previous version to 2.1.0

---

build.sbt

Correctly shade javax.activation

---

build.sbt
project/plugins.sbt

[2.1.x]:  Correctly shade javax.activation

---

.travis.yml
build.sbt

[2.0.x]: Correctly shade javax.activation

---

README.md
bench/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequestBenchMapsBench.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/oauth/OAuth.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StreamedResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Cache.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
play-ws-standalone-xml/src/main/scala/play/api/libs/ws/XMLBodyReadables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyReadables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSRequestFilter.scala

(do not commit there the SBT plugins used to find the errors, only documentation changes)

Fix code examples in markdown documentation & Scaladoc

---

README.md
bench/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequestBenchMapsBench.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/oauth/OAuth.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StreamedResponse.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/Cache.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
play-ws-standalone-json/src/main/scala/play/api/libs/ws/JsonBodyReadables.scala
play-ws-standalone-xml/src/main/scala/play/api/libs/ws/XMLBodyReadables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyReadables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/DefaultBodyWritables.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSRequestFilter.scala
project/Dependencies.scala
project/build.properties

- Backports #424, #428, #429, #430.
- Update Play-JSON to version 2.8.1.

[2.1.x]: Backports and play-json update

---

README.md

Use SystemMaterializer, fix the examples to be compilable.

Doc update java client

---

.mergify.yml

see https://github.com/lagom/lagom/pull/2844

Don't automatically merge Scala Stewards PRs

---

build.sbt
project/AutomaticModuleName.scala

Fixes warnings
- https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
- https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

use slash syntax instead of deprecated `in`

---

build.sbt

re-format `build.sbt`

---

.github/workflows/build-test.yml
.github/workflows/publish.yml
build.sbt

Testing
* https://github.com/playframework/.github/pull/19
Also see
* https://github.com/playframework/playframework/pull/11259 and
* https://github.com/playframework/playframework/pull/11262

Switch to cmd.yml

---

.github/workflows/build-test.yml
.github/workflows/publish.yml
build.sbt
project/plugins.sbt

To cut a new release to fix https://github.com/lightbend/ssl-config/pull/342#issuecomment-1105372744

[2.1.x] sbt-ci-release + GHA

---

build.sbt

Homepage needed for publishing

---

integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/XMLRequestSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSResponseSpec.scala

fix warnings

---

project/Dependencies.scala

Use scala-xml 2.x for Scala 2.13+

---

play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcConfigBuilderSpec.scala

fix test name in AhcConfigBuilderSpec

---

build.sbt
integration-tests/src/test/java/play/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
integration-tests/src/test/scala/play/NettyServerProvider.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestFilterSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/JsonRequestSpec.scala
integration-tests/src/test/scala/play/api/libs/ws/ahc/cache/CachingSpec.scala
integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSClientSpec.scala
integration-tests/src/test/scala/play/libs/ws/ahc/AhcWSRequestFilterSpec.scala
project/Dependencies.scala

avoid `CrossVersion.for3Use2_13`

use play-netty instead akka-http

---

project/Dependencies.scala

https://github.com/scala/scala-xml/releases/tag/v2.2.0
Specially https://github.com/scala/scala-xml/pull/677

scala-xml 2.2.0

---

.github/dependabot.yml
.github/scala-steward.conf
.github/workflows/build-test.yml
.github/workflows/publish.yml
build.sbt

TODO - after merging this pull request:

Preparations on main for 3.0.x branch

---

.github/scala-steward.conf

[3.0.x] Pin Pekko to 1.0.x

---

.github/scala-steward.conf

[2.2.x] Scala Steward: Pin netty-reactive-streams

---

.github/scala-steward.conf

[3.0.x] Scala Steward: Pin netty-reactive-streams

---

build.sbt
play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSClient.java
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala
play-ws-standalone/src/main/scala/play/api/libs/ws/WSConfigParser.scala
project/Dependencies.scala

- Also to make https://github.com/playframework/playframework/pull/11792 work

Switch to jakarta inject
